site_name: SSET
nav:
    - Home: index.md
    - Functions API: func_api.md
    - Field class API: field_api.md
    - Generator classes API: gen_api.md

theme:
  name: "material"
repo_url: https://github.com/rae-holcomb/sset
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: "numpy"
          rendering:
            show_source: false
      custom_templates: templates
      watch:
        - sset